parser/hh_parser/urls.py
from django.urls import path
from hh_parser import views

app_name = 'hh_parser'

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('form/', views.form, name='form'),
    path('contacts/', views.ContactsTemplateView.as_view(), name='contacts'),
    path('results/<str:vacancy>/<str:city>/', views.results, name='results')
]

parser/parser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hh_parser.urls', namespace='parser')),
    path('users/', include('usersapp.urls', namespace='users'))
]

parser/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView

app_name = 'usersapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.CreateRegistrateView.as_view(), name='register'),
]

parser/hh_parser/models.py
from django.db import models

# Create your models here.
class Skill(models.Model):
    name = models.CharField(max_length=16, unique=True)

class Search(models.Model):
    vacancy = models.CharField(max_length=16)
    city = models.CharField(max_length=16)
    count = models.IntegerField()
    sal_from = models.CharField(max_length=14)
    sal_to = models.CharField(max_length=14)

class Requirements(models.Model):
    world_id = models.IntegerField()
    skill_id = models.IntegerField()

parser/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CiteUser(AbstractUser):
    email = models.EmailField(unique=True)

parser/hh_parser/forms.py
from django import forms


class ResultsForm(forms.Form):
    vacancy = forms.CharField(label='Вакансия')
    city = forms.CharField(label='Город')

parser/usersapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CiteUser

class RegistrationForm(UserCreationForm):
    class Meta:
        model = CiteUser
        fields = ('username', 'email')

parser/hh_parser/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import Search, Requirements, Skill
from .forms import ResultsForm
from django.urls import reverse, reverse_lazy
from modules.parsing_modul import hh_parser
from django.views.generic import ListView, FormView, TemplateView
# Create your views here.


class IndexListView(ListView):
    model = Search
    template_name = 'hh_parser/index.html'
    paginate_by = 2


# Не смог придумать, как использовать cbv, так как не нашёл способ достать значения из формы и использовать из в url
# class FormListView(FormView):
#
#     form_class = ResultsForm
#
#     template_name = 'hh_parser/form.html'
#
#     success_url = reverse_lazy('parser:results', kwargs={'vacancy': 'Юрист', 'city': 'Москва'})
    # def get_success_url(self, **kwargs):
    #     return reverse_lazy('parser:results', kwargs={'vacancy': self.kwargs['vacancy'], 'city': self.kwargs['city']})


def form(request):
    if request.method == 'POST':
        form = ResultsForm(request.POST)
        if form.is_valid():
            vacancy = form.cleaned_data['vacancy']
            city = form.cleaned_data['city']

            return HttpResponseRedirect(reverse('parser:results', kwargs={'vacancy': vacancy, 'city': city}))
        else:
            return render(request, 'hh_parser/form.html', context={'form': form})
    else:
        form = ResultsForm()
        return render(request, 'hh_parser/form.html', context={'form': form})


class ContactsTemplateView(TemplateView):
    template_name = 'hh_parser/contacts.html'


# Не смог придумать, как использовать cbv
def results(request, vacancy, city):
    try:
        obj = Search.objects.get(vacancy=vacancy, city=city)
        skills = []
        world_id = obj.id
        for d in Requirements.objects.filter(world_id=world_id).values():
            # print(d, '*'*60)
            id_s = d['skill_id']
            skills.append(Skill.objects.filter(id=id_s).values()[0]['name'])

        if not skills:
            skills = 'Нет информации'
    except:
        data = hh_parser(vacancy, city)
        # print(data)
        obj = data[0]
        skills = data[1]

    return render(request, 'hh_parser/results.html', context={'obj': obj, 'skills': skills})

parser/usersapp/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import RegistrationForm
from .models import CiteUser
# Create your views here.


class UserLoginView(LoginView):
    template_name = 'usersapp/login.html'


class CreateRegistrateView(CreateView):
    model = CiteUser
    template_name = 'usersapp/createregistrate.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')

parser/hh_parser/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="hh.ru parser" />
        <meta name="author" content="Aksey_010" />
        <title>hh.ru parser</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css" >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" >
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">hh.ru parser</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'parser:index' %}">Главная страница</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'parser:form' %}">Поиск по вакансиям</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'parser:contacts' %}">Контактные данные</a>
                    {% if user.is_authenticated %}
                    <form  method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button class="list-group-item list-group-item-action list-group-item-light p-3" type="submit">Выйти из аккаунта</button>
                    </form>
                    {% else %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'users:login' %}">Войти в аккаунт</a>
                    {% endif %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'users:register' %}">Создать аккаунт</a>

                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Спрятать/показать меню</button>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                   {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
    </body>
</html>

parser/hh_parser/templates/hh_parser/contacts.html
{% extends "base.html" %}
{% block content %}
                    <h1 class="mt-4">Контактные данные</h1>
<p>Github: <a href="http://github.com/Aksey010" style="text-decoration:none;" >http://github.com/Aksey010</a></p>
<p>Почта: <a href="mailto:Aksey_new@mail.ru" style="text-decoration:none;">Aksey_new@mail.ru</a></p>
<p>ВК: <a href="https://vk.com/id722967018"  style="text-decoration:none;">Aksey New </a></p>

                    <h1>Понравился сайт? Хотите такой же и даже лучше?</h1>
                    <p>Обращайтесь по перечисленным выше почте и соцсетям. Также предоставляются услуги по созданию телеграмм-ботов и интеграции нейросетей.</p>
{% endblock %}

parser/hh_parser/templates/hh_parser/form.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
                    <h1 class="mt-4">Поиск по вакансиям</h1>
                   <form action=""   method="POST">
                       {% csrf_token %}
                       {% for field in form %}
                       <p>{{field.label_tag}}</p>
                       {% for error in field.errors %}
                           {{error}}
                       {% endfor %}
                       <p>{{field}}</p>
                       {% endfor %}
    <input type="submit" value="Искать">
</form>
                    <br>
                    <p><b>Внимание:</b> Поиск может занимать до пары минут</p>
{% else %}
<h1 class="mt-4">Поиск по вакансиям</h1>
<h4 class="mt-4">Вы не вошли в аккаунт</h4>
Пожалуйста, <a href="{% url 'users:login' %}">войдите в аккаунт</a>. Если у вас нет аккаунта, создать его можно <a href="{% url 'users:register' %}"> здесь</a>.
{% endif %}
{% endblock %}

parser/hh_parser/templates/hh_parser/index.html
{% extends "base.html" %}
{% block content %}
                    <h1 class="mt-4">Главная страница</h1>
<h5 class="mt-4">Добро пожаловать, {{user.username}}</h5>
                    <p>Этот парсер может выводить сводку о количестве вакансий, их средней зарплате и пяти самых требуемых навыках, которые для них требуются.</p>
<p>Чтобы воспользоваться парсером, надо ввести вакансию, по которой он будет искать, и выбрать город из списка. </p>

<h1 class="mt-4">Все запросы</h1>
{% for search in page_obj %}
<ul>
    <li>{{ search.vacancy }}<br>
    {{ search.city }}<br>
    {{ search.count }}<br>
    {{ search.sal_from }}<br>
    {{ search.sal_to }}</li>
</ul>
<hr>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

parser/hh_parser/templates/hh_parser/results.html
{% extends "base.html" %}
{% block content %}

                <h4>Запрос:</h4>
            <p>{{obj.vacancy}}<br>
                {{obj.city}}
                </p>
                <h4>Количество вакансий</h4>
            <p>{{obj.count}}</p>
                <h4>Средняя зарплата в рублях</h4>
            <p>От {{obj.sal_from}}
                <br />
                До {{obj.sal_to}} </p>
                <h4>Самые часто требуемые навыки</h4>
                <ul>
                    {% for skill in skills %}
                <li>{{ skill }}
                    {% endfor %}
                </ul>
{% endblock %}

parser/usersapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="hh.ru parser" />
        <meta name="author" content="Aksey_010" />
        <title>hh.ru parser</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css" >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" >
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">hh.ru parser</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'parser:index' %}">Главная страница</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'parser:form' %}">Поиск по вакансиям</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'parser:contacts' %}">Контактные данные</a>
                    {% if user.is_authenticated %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'users:logout' %}">Выйти из аккаунт</a>
                    {% else %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'users:login' %}">Войти в аккаунт</a>
                    {% endif %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'users:register' %}">Создать аккаунт</a>

                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Спрятать/показать меню</button>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                   {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
    </body>
</html>

parser/usersapp/templates/usersapp/createregistrate.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}

parser/usersapp/templates/usersapp/login.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
</form>
{% endblock %}

parser/usersapp/templates/usersapp/logout.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="hh.ru parser" />
        <meta name="author" content="Aksey_010" />
        <title>hh.ru parser</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css" >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" >
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">hh.ru parser</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/">Главная страница</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/form">Поиск по вакансиям</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/contacts">Контактные данные</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Спрятать/показать меню</button>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                   {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
    </body>
</html>